---
- hosts: all
  become_method: sudo
  become: yes
  become_user: root

  vars:
    nfs_share_folder: /srv/nfsshare

  tasks:
    - name: insall nfs-utils
      yum:
        name: nfs-utils
        state: present

    - name: ensure nfs-share exists
      file: >
        path="{{ nfs_share_folder }}"
        state=directory
        mode=0777
        owner=nfsnobody
        group=nfsnobody
        recurse=true

    - name: start the services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - rpcbind
        - nfs-server
        - nfs-lock
        - nfs-idmap

    - name: export the folder
      template:
        src: exports.j2
        dest: /etc/exports
      notify:
        - restart nfs

  handlers:
    - name: restart nfs
      service:
        name: nfs-server
        state: restarted
